### ISSUE TITLE
Screenshot links broken

### ISSUE THREAD

**Issue by TingPing** [flathub/nl.hjdskes.gcolor3#1]
Missed in review but they 404: https://raw.githubusercontent.com/Hjdskes/gcolor3/blob/v2.3/picker.png

**Comment by qwertychouskie** [comment]
See https://github.com/Hjdskes/gcolor3/pull/104

**Comment by Hjdskes** [comment]
@TingPing With the AppData file now fixed, what is the best way forward? Tag a 2.3.1 release with https://github.com/Hjdskes/gcolor3/pull/104 included?

**Comment by TingPing** [comment]
Up to you, its fine to just add a patch here but if the appdata file is used elsewhere might as well get it in a release.

**Comment by Hjdskes** [comment]
I will release a 2.3.1 tomorrow, then. It's 1.44 AM here...

**Comment by Hjdskes** [comment]
Waiting to see if https://github.com/Hjdskes/gcolor3/issues/105 can make it in for 2.3.1 as well.
